# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'HERBALIFE.ACR'
    repository: 'andresnet-producer'
    tags: latest
    command: 'buildAndPush'
    Dockerfile: 'apps/net/kafka.producer/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'HERBALIFE.ACR'
    repository: 'andresnet-consumer'
    tags: latest
    command: 'buildAndPush'
    Dockerfile: 'apps/net/kafka.consumer/Dockerfile'    
    
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'HERBALIFE.AKS'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'manifests/producer-deployment.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'HERBALIFE.AKS'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'manifests/consumer-deployment.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'    