
version: '3.4'

services:
  net-producer:
    image: net-producer
    build:
      context: apps/net/kafka.producer
      dockerfile: ./Dockerfile
  net-consumer:
    image: net-consumer
    build:
      context: apps/net/kafka.consumer
      dockerfile: ./Dockerfile      
