apiVersion: apps/v1
kind: Deployment
metadata:
  name: andresnet-consumer
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: andresnet-consumer
  template:
    metadata:
      labels:
        app: andresnet-consumer
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: andresnet-consumer
          image: herbalifeacr.azurecr.io/andresnet-consumer:latest
          ports: []
          resources:
            requests:
              cpu: '0'
              memory: '0'
            limits:
              cpu: '256'
              memory: 11400G
