apiVersion: apps/v1
kind: Deployment
metadata:
  name: andresnet-producer
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: andresnet-producer
  template:
    metadata:
      labels:
        app: andresnet-producer
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: andresnet-producer
          image: herbalifeacr.azurecr.io/andresnet-producer:latest
          ports: []
          resources:
            requests:
              cpu: '0'
              memory: '0'
            limits:
              cpu: '256'
              memory: 11400G
